<?php require 'templates/header.phtml' ?>

<form id="form" action="editado/<?=$id?>" method="POST" class="my-4">
        <label >Producto</label>
        <input name="Nombre" type="text">
        <label>Precio</label>
        <input name="Precio" type="number" min="1">
        <label for="CategoriaID" class="form-label">Categoria</label>
             <select name="CategoriaID" class="form-select" id="CategoriaID" aria-label="Seleccione categoría" required>
                 <option selected>Seleccione categoría</option>
                     <?php foreach ($categorias as $categoria): ?>
                 <option value="<?= $categoria->CategoriaID?>"><?= $categoria->Nombre?></option>
                    <?php endforeach; ?>
            </select>
        <input type="submit">
    </form>


<?php require 'templates/footer.phtml' ?>