<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tu Tienda en Línea</title>
   
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <base href="<?php echo BASE_URL?>">
</head>
<body>
    <header>
    <div class="container">
        <h1 class="text-center">...</h1>
        <h2 class="text-center">Nuestros Productos: </h2>
    </div>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <h3 class="navbar-brand" href="index.php">Tu Tienda</h3>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                        <a class="nav-link" href="home">Home</a>
                        </li>
                        <li class="nav-item">
                            <?php if (isset($_SESSION['USER_ID'])) { ?>
                                <a class="nav-link" href="agregar">Agregar producto</a>
                            <?php } ?>
                        </li>
                        <div class="dropdown">
                <button class="btn btn-primary dropdown-toggle" type="button" id="categoriasDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Categorías
                </button>
                <div class="dropdown-menu" aria-labelledby="categoriasDropdown">
                    <a class="dropdown-item" href="categorias">Lista</a>
                    <a class="dropdown-item" href="agregarcat">Agregar</a>
                </div>
                </div>

                    </ul>
                </div>
            </div>
            <?php if (!isset($_SESSION['USER_ID'])) : ?>
                <a href="login" type="button" class="btn btn-dark float-end pr" id="boton-login">Login</a>
            <?php else : ?>
                <a href="logout" type="button" class="btn btn-dark float-end" id="boton-login">Logout(<?= $_SESSION['USER_USER'] ?>)</a>
            <?php endif ?>
        </nav>
    </header>

    
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>