<?php require 'templates/header.phtml' ?>

<h1 class="text-center">Categorías</h1>
    <div class="row">
        <?php foreach ($categorias as $categoria):?>
            <div class="col-md-4 mb-4">
                <div class="card h-100 d-flex justify-content-center align-items-center">
                    <div class="card-body text-center">
                        <h5 class="card-title"><?= htmlspecialchars($categoria->Nombre) ?></h5>
                        <?php if (isset($_SESSION['USER_ID'])) { ?>
                        <a href="editarcat/<?= $categoria->CategoriaID ?>" class="btn btn-primary btn-sm">Editar Categoria</a>
                        <a href="borrarcat/<?= $categoria->CategoriaID ?>" class="btn btn-primary btn-sm">Borrar Categoria</a>
                        <?php } ?>
                    </div>
                </div>
            </div>
        <?php endforeach?>
    </div>
</div>

<?php require 'templates/footer.phtml' ?>